environment: "development"

application:
  version: "0.1.0"

server:
  port: 7546
  type: "http"

hedera:
  network: "testnet"
  networkConfig:
    "127.0.0.1:50211": "0.0.3"
  operatorId: "0.0.5425484"
  operatorKey: "3030020100300706052b8104000a042204209d674f6e14d913487b4c3f43aa372a3b81dc7708b76a6d082c37c1ea5cbeb064"
  operatorKeyFormat: "DER"
  chainId: "0x128" # always pass this as a hex
  hbarBudget: 5000000000

mirrorNode:
  baseUrl: "https://testnet.mirrornode.hedera.com"
  web3Url: "https://testnet.mirrornode.hedera.com"
  timeoutSeconds: 90000
limiter:
  free:
    requestsPerMinute: 1000000
    hbarLimit: 5000000000
  premium:
    requestsPerMinute: 1000
    hbarLimit: 10000

logging:
  level: "debug"
  DisableCaller: true

apiKeys:
  - key: "FREE-USER-API-KEY-123"
    tier: "free"
  - key: "PREMIUM-USER-API-KEY-456"
    tier: "premium"

features:
  enforceApiKey: false
  filterApiEnabled: true
  debugApiEnabled: true

cache:
  defaultExpiration: "1h"
  cleanupInterval: "30m"