name: CI - Dev Tool Tests

on:
  pull_request:
    branches: [ main, release/** ]
  push:
    branches: [ main, release/** ]
    tags: [ v* ]

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  hardhat:
    name: Hardhat
    uses: ./.github/workflows/dev-tool-workflow.yml
    with:
      command: cp hardhat.config.ts.example hardhat.config.ts && npx hardhat test --network testnet
      directory: ./tools/hardhat
